name: lifebonder
description: A life bonder task.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  # Local Data Storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0 # provide extension for hive
  # For importing svg
  flutter_svg: ^2.0.9
  # For network calls
  dio: ^5.4.0
  # Console beautifier
  logger: ^2.0.2+1  
  # For state management
  flutter_bloc: ^8.1.3
  # Service locator
  get_it: ^7.6.4
  # Code generator for get_it
  injectable: ^2.3.2
  # For dev annotations
  meta: ^1.9.1
  # For data-driven routes
  go_router: ^12.1.1
  # Compare objects equlality
  equatable: ^2.0.5
  # Functional programming thingies
  dartz: ^0.10.1
  # Code generation for immutable classes (Data Class)
  freezed_annotation: ^2.4.1
  # For flutter Toast
  cherry_toast: ^1.6.4
  # For checking data connection
  data_connection_checker:
    git:
      url: https://github.com/w830207/data_connection_checker
      ref: noPedantic


dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.7
  # For writing unit tests
  mockito: ^5.4.2
  # Freezed
  freezed: ^2.4.5
  json_serializable: ^6.7.1
  # Hive generator
  hive_generator: ^2.0.1
  # Injectable generator
  injectable_generator: ^2.4.1
  # For improving code
  flutter_lints: ^3.0.1

  http_mock_adapter: ^0.6.0


# The following section is specific to Flutter packages.
flutter:

  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/

